apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: webserver
  type: NodePort