apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always #https://kubernetes.io/docs/concepts/configuration/overview/
        env:
        - name: MYSQL_PASSWORD
          value: Clarusway_1
        - name: MYSQL_ROOT_PASSWORD
          value: "123456e"
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_DATABASE
          value: clarusway
        ports:
        - containerPort: 3306



