apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webserver
  template:
    metadata:
      name: webserver
      labels:
        name: webserver
    spec:
      containers:
        - name: api-app
          image: elifadmin/webserver
          imagePullPolicy: Always
          ports:
          - containerPort: 80
          env:
          - name: MYSQL_PASSWORD
            value: Clarusway_1
          - name: MYSQL_USER
            value: admin
          - name: MYSQL_DATABASE
            value: mysql-deploy
          - name: MYSQL_DATABASE_HOST
            value: mysql-service